### ISSUE TITLE
Missing content folder

### ISSUE THREAD

**Issue by bep** [digitalcraftsman/hugo-hikari-theme#1]
Could you check all your exampleSite in your themes and make sure they have the needed content folders.

Or, better, check them in "Hugo Theme Site" and make sure they look OK. 

This gets pretty old pretty quick if I have to open up a lot of pull requests for these.

**Comment by digitalcraftsman** [comment]
Sorry for that. Fixed this in c3669837151ea1562127d798ea5785b2bada454d. For future developement I'll create a gist with a todo list and add this point to it.
