### ISSUE TITLE
Missing content in exampleSite

### ISSUE THREAD

**Issue by bep** [digitalcraftsman/hugo-hikari-theme#2]
I think this also applies to another of your sites. If you, for some reason, want to provide an exampleSite -- it should have some generic content so the front page isn't blank.

**Comment by digitalcraftsman** [comment]
This also applies to the cactus theme. Usually your script adds demo content to all themes that don't provide an exampleSite directory. Concluded does this mean that I need to add the content myself until I make use of exampleSite, right?

**Comment by bep** [comment]
exampleSite = standalone hugo site. Nothing added, i.e. the opposite of what you say.

**Comment by digitalcraftsman** [comment]
I've added demo content to both themes.
