### ISSUE TITLE
404 error prevents me from using the theme.

### ISSUE THREAD

**Issue by float-mode** [digitalcraftsman/hugo-hikari-theme#3]
Installed Hugo for the first time 2 hours ago. So I'm a hugo baby you may say. This is probably some super basic stuff, yet I have no clue how to fix it... Hikari seems like an awesome theme and really wanted to give it a try, but unlike any other theme I tried so far, I'm unable to get hikari to work as I get this error:

```
$ hugo server --theme=hikari --buildDrafts
ERROR: 2015/10/12 Error while rendering 404 page: template: theme/404.html:11:100: executing "theme/404.html" at <markdownify>: wrong number of args for markdownify: want 1 got 0
```

**Comment by digitalcraftsman** [comment]
I've tested the theme myself and no error occured. After trying different test scenarios I maybe found the issue. Could it be possible that you accidently deleted the following lines from the config file:

``` toml
pageNotFoundTitle = ""
pageNotFoundSubtitle = ""
```

Even if both variables are empty I don't get an error message. Only if I remove them completely. Could you check your config file?

**Comment by crsqq** [comment]
@digitalcraftsman
I think this issue can be closed. I had the same problem and it was due to the missing entries
`pageNotFoundTitle` and `pageNotFoundSubtitle`.

**Comment by digitalcraftsman** [comment]
Hi @crsqq,

thanks for confirming that my comment above should work. Therefore, I'll close this issue.

@float-mode, if you still have problems, please reopen this issue.
